---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
library(dplyr)
library(lubridate)
activity_data <- read.csv("activity.csv") %>%
  # Convert integer intervals to time values so we can plot them properly.
  # TODO(laixer): Any easier way to do this?
  mutate(interval = origin + 60 * (60 * (interval %/% 100) + interval %% 100))
```

## What is mean total number of steps taken per day?

```{r}
library(dplyr)
library(ggplot2)
steps_by_date <- 
  activity_data %>% 
  filter(!is.na(steps)) %>% 
  group_by(date) %>% 
  summarize(total_steps = sum(steps))
ggplot(steps_by_date, aes(total_steps)) + geom_histogram(binwidth = 1000)
mean(steps_by_date$total_steps)
median(steps_by_date$total_steps)
```

## What is the average daily activity pattern?

```{r}
library(scales)
steps_by_interval <- 
  activity_data %>% 
  filter(!is.na(steps)) %>% 
  group_by(interval) %>% 
  summarize(mean_steps = mean(steps))
ggplot(steps_by_interval, aes(interval, mean_steps)) + 
  geom_point() + 
  geom_line() + 
  scale_x_datetime(labels = date_format("%H:%M"))
format(steps_by_interval$interval[which.max(steps_by_interval$mean_steps)], format = "%H:%M")
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
